services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-gaycarboys}
      MYSQL_USER: ${DB_USER:-gaycarboys}
      MYSQL_PASSWORD: ${DB_PASSWORD:-gaycarboys}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3-apache
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-gaycarboys}
      WORDPRESS_DB_USER: ${DB_USER:-gaycarboys}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-gaycarboys}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WP_DEBUG:-true}
    volumes:
      - ./wordpress:/var/www/html
      - ./config/wp-config-local.php:/var/www/html/wp-config.php

  wpcli:
    image: wordpress:cli-php8.3
    depends_on:
      - db
      - wordpress
    user: "33:33" # www-data
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-gaycarboys}
      WORDPRESS_DB_USER: ${DB_USER:-gaycarboys}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-gaycarboys}
    volumes:
      - ./wordpress:/var/www/html
      - ./config/wp-config-local.php:/var/www/html/wp-config.php
    working_dir: /var/www/html

volumes:
  db_data:


